name: Check for changes in cp.yml and push to main
on:
  push:
    # branches:
    #   - dev
    paths:
      - '.github/workflows/cp.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Run if cp.yml has changed
        run: |
          echo "List of branches:"
          git branch -a
          git config user.email jerry-lee@webglsoft.com
          git config user.name jerry-lee@GLSoft
          git checkout remotes/origin/cicd-test-prod -- .github/workflows/cp.yml
          git commit -m "Update cp.yml"
          git push