name: Check for changes in cp.yml and push to main
on:
  push:
    # branches:
    #   - dev
    paths:
      - '.github/workflows/cp.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Run if cp.yml has changed
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'youremail@example.com'
          git checkout main -- .github/workflows/cp.yml
          git commit -m "Update cp.yml"
          git push