name: Run deck-def
on:
  push:
    branches:
      - 'main'
    paths:      
      - 'deck/**'
# env:
#   DEF_CHANGED: ${{ github.event_name == 'push' }}
#   CP_CONF_CHANGED: ${{ contains(github.event.commits[0].modified, 'kong-conf/') }}
#   JS_CHANGED: ${{ contains(github.event.commits[0].modified, 'js/') }}

jobs:
  check_run:
      runs-on: kong
    steps:
    - name: Check if files in kong-conf/, js/ or deck/ were modified
      run: |
        should_run-all=false
        should_run-vm=false
        should_run-deck=false
        if [[ "${{ join(github.event.commits[0].modified, ' ') }}" =~ "kong-conf/" ]] && [[ "${{ join(github.event.commits[0].modified, ' ') }}" =~ "js/" ]] && [[ "${{ join(github.event.commits[0].modified, ' ') }}" =~ "def/" ]]; then
          should_run-all=true
          echo "Files in kong-conf/, js/ and deck/ were modified"
        elif [[ "${{ join(github.event.commits[0].modified, ' ') }}" =~ "kong-conf/" ]] && [[ "${{ join(github.event.commits[0].modified, ' ') }}" =~ "js/" ]]; then
          should_run-vm=true
          echo "Files in kong-conf/ and js/ were modified"
        elif [[ "${{ join(github.event.commits[0].modified, ' ') }}" =~ "deck/" ]]; then
          should_run-deck=true
          echo "Files in deck/ were modified"
        else
          echo "No files in kong-conf/, js/ or deck/ were modified"
        fi
        echo "should_run-all=$should_run-all" >> $GITHUB_ENV
        echo "should_run-vm=$should_run-vm" >> $GITHUB_ENV
        echo "should_run-deck=$should_run-deck" >> $GITHUB_ENV

    deploy-def:
      needs: check_run
      if: env.should_run-deck == 'true'
      runs-on: kong
      name: Deploying Kong Configuration
      environment: play
      steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "16"

      - name: Display decK Version
        run: deck version

      - name: Backup existing configuration for a specific tag
        run: deck dump -o kong-dev.yaml --tls-skip-verify
        env:
          DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
          DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}

      - name: Validate Deck Config File
        run: deck validate -s ./deck

      - name: Compare Configurations
        run: deck diff  -s ./deck --tls-skip-verify
        env:
          DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
          DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}

      - name: Apply new configuration
        run: deck sync  -s ./deck --tls-skip-verify
        env:
          DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
          DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}

      - name: Back out changes on failure
        if: ${{ failure() }}
        run: deck sync  -s kong-dev.yaml  --tls-skip-verify
        env:
          DECK_KONG_ADDR: ${{ secrets.KONG_ADMIN_API_URL }}
          DECK_HEADERS: ${{ secrets.KONG_DECK_HEADERS }}
